import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

// TODO: Refactor the Metadata object to dynamically generate the title and description
// based on the page's specific content. Ensure each page can customize its metadata accordingly.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="flex min-h-screen flex-col items-center justify-between pt-20 pb-16 m-auto max-w-[1024px]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
